// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const getAboutMe = `-- name: GetAboutMe :one
SELECT aboutMe FROM assets
WHERE id = ?
`

func (q *Queries) GetAboutMe(ctx context.Context, id int32) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getAboutMe, id)
	var aboutme sql.NullString
	err := row.Scan(&aboutme)
	return aboutme, err
}

const getTitle = `-- name: GetTitle :one
SELECT title FROM assets
WHERE id = ?
`

func (q *Queries) GetTitle(ctx context.Context, id int32) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getTitle, id)
	var title sql.NullString
	err := row.Scan(&title)
	return title, err
}
