apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "zex-app.backend.fullname" . }}
  labels:
    {{- include "zex-app.labels" (dict "context" . "component" .Values.backend.name "name" .Values.backend.name) | nindent 4 }}
  namespace: {{ include "zex-app.namespace" (dict "name" .Values.backend.name "context" .) }}
spec:
  podSelector:
    matchLabels:
      {{- include "zex-app.labels" (dict "context" . "component" .Values.backend.name "name" .Values.backend.name) | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "zex-app.labels" (dict "context" . "component" .Values.frontend.name "name" .Values.frontend.name) | nindent 14 }}
        - namespaceSelector:
            matchLabels:
              {{- include "zex-app.namespaceLabelSelector" (dict "context" . "name" .Values.frontend.name) | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.backend.service.http.port }}
        - protocol: TCP
          port: {{ .Values.backend.service.https.port }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              {{- include "zex-app.namespaceLabelSelector" (dict "context" . "name" .Values.database.name) | nindent 14 }}
        - podSelector:
            matchLabels:
              {{- include "zex-app.labels" (dict "context" . "component" .Values.database.name "name" .Values.database.name) | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.database.service.mysql.port }}
