apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zex-app.backendServiceAccountName" . }}
  labels:
    {{- include "zex-app.labels" (dict "context" . "component" .Values.backend.name "name" .Values.backend.name) | nindent 4 }}
  namespace: {{ include "zex-app.namespace" (dict "name" .Values.backend.name "context" . ) }}
  {{- with .Values.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.backend.serviceAccount.automountServiceAccountToken }}
