{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zex-app.database.fullname" . }}
  labels:
    {{- include "zex-app.labels" (dict "context" . "component" .Values.database.name "name" .Values.database.name) | nindent 4 }}
  namespace: {{ include "zex-app.namespace" (dict "name" "database" "context" .) }}
type: Opaque
data:
  mysql-root-password: {{ randAlphaNum 20 | nospace | b64enc }}
  mysql-user-password: {{ randAlphaNum 20 | nospace | b64enc }}
{{- end }}