{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zex-app.database.fullname" . }}
  labels:
    {{- include "zex-app.labels" (dict "context" . "component" .Values.database.name "name" .Values.database.name) | nindent 4 }}
    app.kubernetes.io/version: {{ .Values.database.image.tag }}
  namespace: {{ include "zex-app.namespace" (dict "name" "database" "context" .) }}
spec:
  serviceName: {{ include "zex-app.database.fullname" . }}
  {{- if not .Values.database.autoscaling.enabled }}
  replicas: {{ .Values.database.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zex-app.selectorLabels" (dict "context" . "component" .Values.database.name "name" .Values.database.name) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.database.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zex-app.labels" (dict "context" . "component" .Values.database.name "name" .Values.database.name) | nindent 8 }}
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.database.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.database.serviceAccount.create }}
      serviceAccountName: {{ include "zex-app.databaseServiceAccountName" . }}
      {{- end }}
      {{- if .Values.database.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.database.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.database.name }}
          {{- if .Values.database.securityContext }}
          securityContext:
            {{- toYaml .Values.database.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag | default .Chart.AppVersion }}"
          env:
            - name: "MARIADB_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ include "zex-app.database.fullname" . }}
                  key: mysql-root-password
            - name: "MARIADB_DATABASE"
              value: {{ .Values.database.databaseName }}
            - name: "MARIADB_USER"
              value: {{ .Values.database.databaseUser }}
            - name: "MARIADB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ include "zex-app.database.fullname" . }}
                  key: mysql-user-password
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          ports:
            - name: {{ .Values.database.service.mysql.name | quote }}
              containerPort: {{ .Values.database.service.mysql.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-ec"
                - "mariadb -p$MARIADB_ROOT_PASSWORD -e 'SELECT 1'"
            {{- toYaml .Values.database.livenessProbe | nindent 12 }}
          readinessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-ec"
                - "mariadb -p$MARIADB_ROOT_PASSWORD -e 'SELECT 1'"
            {{- toYaml .Values.database.readinessProbe | nindent 12 }}
          {{- if .Values.database.resources }}
          resources:
            {{- toYaml .Values.database.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /etc/mysql/conf.d
          {{- with .Values.database.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "zex-app.database.fullname" . }}
            items:
              - key: my.cnf
                path: my.cnf
        - name: data
          persistentVolumeClaim:
            claimName: data
      {{- with .Values.database.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.database.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.database.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.database.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.database.persistence.persistentVolumeClaimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy:
    {{ toYaml  . | nindent 4 }}
  {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "zex-app.labels" (dict "context" . "component" .Values.database.name "name" .Values.database.name) | nindent 10 }}
      spec:
        volumeMode: Filesystem
        {{- if .Values.database.persistence.storageClassName }}
        storageClassName: {{ .Values.database.persistence.storageClassName }}
        {{- end }}
        accessModes:
          {{- range .Values.database.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
           requests:
             storage: {{ .Values.database.persistence.storageSize }}
        {{- if .Values.database.persistence.selector }}
        selector:
          {{- range .Values.database.persistence.selector }}
            {{ toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}

{{- end }}