apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "zex-app.frontend.fullname" . }}
  labels:
    {{- include "zex-app.labels" (dict "context" . "component" .Values.frontend.name "name" .Values.frontend.name) | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "zex-app.labels" (dict "context" . "component" .Values.frontend.name "name" .Values.frontend.name) | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: "ingress-nginx"
      ports:
        - protocol: TCP
          port: {{ .Values.frontend.service.http.port }}
        - protocol: TCP
          port: {{ .Values.frontend.service.https.port }}
  egress:
    - to:
        - ipBlock:
            cidr: "0.0.0.0/0"
            except:
              - "10.0.0.0/8"
              - "172.16.0.0/12"
              - "192.168.0.0/16"
    - to:
      - podSelector:
          matchLabels:
            {{- include "zex-app.labels" (dict "context" . "component" .Values.backend.name "name" .Values.backend.name) | nindent 14 }}
      - namespaceSelector:
          matchLabels:
            {{- include "zex-app.namespaceLabelSelector" (dict "context" . "name" .Values.backend.name) | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.backend.service.http.port }}
        - protocol: TCP
          port: {{ .Values.backend.service.https.port }}
