apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "zex-app.secretsReaderRoleName" . }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]